service: api-node-matrices

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    DB_SSL: ${env:DB_SSL}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
